#!/usr/bin/env node

var crypto = require('crypto');

var algorithm = 'aes256';
var data = process.argv[3];
var key = process.argv[4];

var crypt = function(){
  if (!(data && key)) return console.log("No filename or key.");

  var cipher = crypto.createCipher(algorithm, key);  
  var encrypted = cipher.update(data, 'utf8', 'hex') + cipher.final('hex');

  console.log(encrypted);
}

var decrypt = function(){
  if (!(data && key)) return console.log("No filename or key.");

  var decipher = crypto.createDecipher(algorithm, key);
  var decrypted = decipher.update(data, 'hex', 'utf8') + decipher.final('utf8');

  console.log(decrypted);
}

if (process.argv[2] === "-c") crypt();
else if (process.argv[2] === "-d") decrypt();